# Generated by Django 4.2.3 on 2023-07-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_auto_20200528_1749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chambre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
