# Generated by Django 3.2 on 2023-07-26 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0009_auto_20230726_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date(2023, 7, 26))),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.IntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date(2023, 7, 26))),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('amount_remain', models.IntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 7, 26))),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reservation')),
            ],
        ),
    ]
