# Generated by Django 3.2 on 2023-07-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20230726_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='date',
            field=models.DateField(default='2023-07-26'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2023-07-26'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='date',
            field=models.DateField(default='2023-07-26'),
        ),
    ]
