# Generated by Django 3.2 on 2023-07-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_auto_20230727_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sells',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sells',
            name='original_amount',
        ),
        migrations.RemoveField(
            model_name='sells',
            name='reservation',
        ),
    ]
