# Generated by Django 3.2 on 2023-07-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20230727_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='date',
            field=models.DateField(default='2023-07-31'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default='2023-07-31'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='date',
            field=models.DateField(default='2023-07-31'),
        ),
    ]
