# Generated by Django 4.2 on 2023-08-14 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admins", "0010_alter_debts_date_alter_expenses_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debts",
            name="date",
            field=models.DateField(default="2023-08-14"),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="date",
            field=models.DateField(default="2023-08-14"),
        ),
        migrations.AlterField(
            model_name="sells",
            name="date",
            field=models.DateField(default="2023-08-14"),
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("date", models.DateField(default="2023-08-14")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
