# Generated by Django 4.2 on 2023-08-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0011_alter_debts_date_alter_expenses_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debts",
            name="reservation",
        ),
        migrations.DeleteModel(
            name="Sells",
        ),
        migrations.DeleteModel(
            name="Debts",
        ),
    ]
