# Generated by Django 4.2 on 2023-08-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0012_remove_debts_reservation_delete_sells_delete_debts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="date",
            field=models.DateField(default="2023-08-16"),
        ),
        migrations.AlterField(
            model_name="salary",
            name="date",
            field=models.DateField(default="2023-08-16"),
        ),
    ]
