# Generated by Django 4.2 on 2023-08-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0013_alter_expenses_date_alter_salary_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default="2023-08-16")),
                ("sent", models.BooleanField(default=False)),
            ],
        ),
    ]
