# Generated by Django 4.2.3 on 2023-07-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Phone", models.IntegerField(default=0)),
                ("Email", models.EmailField(max_length=40)),
                ("days_of_staying", models.IntegerField(default=0)),
                (
                    "Date_Check_In",
                    models.DateTimeField(verbose_name="2023-47-21 18:47:45"),
                ),
                ("Date_Check_Out", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="media/pics")),
                ("price", models.IntegerField(default=0)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="media/pics")),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Phone", models.IntegerField(default=0)),
                ("Email", models.EmailField(max_length=40)),
                ("days_of_staying", models.IntegerField(default=0)),
                (
                    "Date_Check_In",
                    models.DateTimeField(verbose_name="2023-47-21 18:47:45"),
                ),
                ("Date_Check_Out", models.DateField(blank=True, null=True)),
                ("Check_Out", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("reserved", models.BooleanField(default=False)),
                ("booked", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.categories",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Chambre",
        ),
        migrations.AddField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.rooms"
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="home.reservation"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.rooms"
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="home.reservation"
            ),
        ),
    ]
