# Generated by Django 4.2.3 on 2023-07-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_billing_booking_categories_debt_gallery_reservation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_In",
            field=models.DateTimeField(verbose_name="2023-09-21 22:09:52"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_In",
            field=models.DateTimeField(verbose_name="2023-09-21 22:09:52"),
        ),
    ]
