# Generated by Django 4.2.3 on 2023-07-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_booking_booking_code_alter_booking_date_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_In",
            field=models.DateField(verbose_name="2023-34-22 20:34:22"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_In",
            field=models.DateTimeField(verbose_name="2023-34-22 20:34:22"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Email",
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
