# Generated by Django 4.2.3 on 2023-07-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_booking_date_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_In",
            field=models.DateField(verbose_name="2023-36-22 20:36:49"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_In",
            field=models.DateField(default="2023-36-22 20:36:49"),
        ),
    ]
