# Generated by Django 4.2.3 on 2023-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_booking_date_check_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="booking_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_In",
            field=models.DateField(verbose_name="2023-07-23"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_In",
            field=models.DateField(default="2023-07-23"),
        ),
    ]
