# Generated by Django 3.2 on 2023-07-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230723_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancel_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancel_book_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
