# Generated by Django 3.2 on 2023-07-26 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230723_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='check_out_on',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='days_of_staying',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_on',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='reserved',
        ),
        migrations.AddField(
            model_name='reservation',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date_Check_In',
            field=models.DateField(verbose_name=datetime.date(2023, 7, 26)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Date_Check_In',
            field=models.DateField(default=datetime.date(2023, 7, 26)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booked_on',
            field=models.DateField(blank=True, default=datetime.date(2023, 7, 26), null=True),
        ),
    ]
