# Generated by Django 3.2 on 2023-07-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230726_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date_Check_In',
            field=models.DateField(verbose_name='2023-07-26'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Date_Check_In',
            field=models.DateField(default='2023-07-26'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booked_on',
            field=models.DateField(blank=True, default='2023-07-26', null=True),
        ),
    ]
