# Generated by Django 3.2 on 2023-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230726_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date_Check_In',
            field=models.DateField(verbose_name='2023-07-27'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Date_Check_In',
            field=models.DateField(default='2023-07-27'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booked_on',
            field=models.DateField(blank=True, default='2023-07-27', null=True),
        ),
    ]
