# Generated by Django 3.2 on 2023-07-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230727_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
