# Generated by Django 3.2 on 2023-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rooms_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.CharField(blank=True, choices=[('PAID', 'PAID'), ('DEBT', 'DEBT')], max_length=50, null=True),
        ),
    ]
