# Generated by Django 3.2 on 2023-07-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_reservation_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='update_at',
            field=models.DateField(blank=True, default='2023-07-27', null=True),
        ),
    ]
