# Generated by Django 3.2 on 2023-07-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_reservation_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='billing',
            name='paid_on',
            field=models.DateField(default='2023-07-31'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date_Check_In',
            field=models.DateField(verbose_name='2023-07-31'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Date_Check_In',
            field=models.DateField(default='2023-07-31'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booked_on',
            field=models.DateField(blank=True, default='2023-07-31', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='update_at',
            field=models.DateField(blank=True, default='2023-07-31', null=True),
        ),
    ]
