# Generated by Django 3.2 on 2023-07-31 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20230731_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reservation'),
        ),
    ]
