# Generated by Django 4.2 on 2023-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_alter_billing_paid_on_alter_booking_date_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="paid_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
