# Generated by Django 4.2 on 2023-08-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_billing_paid_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_In",
            field=models.DateField(verbose_name="2023-08-07"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="Phone",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_In",
            field=models.DateField(default="2023-08-07"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="booked_on",
            field=models.DateField(blank=True, default="2023-08-07", null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="update_at",
            field=models.DateField(blank=True, default="2023-08-07", null=True),
        ),
    ]
