# Generated by Django 4.2 on 2023-08-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_alter_booking_date_check_in_alter_booking_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="paid_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_In",
            field=models.DateTimeField(verbose_name="2023-08-08 15:08"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_Out",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_In",
            field=models.DateTimeField(default="2023-08-08 15:08"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_Out",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="booked_on",
            field=models.DateTimeField(
                blank=True, default="2023-08-08 15:08", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancel_book_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="paid_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="update_at",
            field=models.DateTimeField(
                blank=True, default="2023-08-08 15:08", null=True
            ),
        ),
    ]
