# Generated by Django 4.2 on 2023-08-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_alter_billing_paid_on_alter_booking_date_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="paid_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_In",
            field=models.DateField(verbose_name="2023-08-08"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_Out",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_In",
            field=models.DateField(default="2023-08-08"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_Out",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="booked_on",
            field=models.DateField(blank=True, default="2023-08-08", null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cancel_book_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="paid_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="update_at",
            field=models.DateField(blank=True, default="2023-08-08", null=True),
        ),
    ]
