# Generated by Django 4.2 on 2023-08-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_alter_billing_paid_on_alter_booking_date_check_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="created_at",
            field=models.DateField(default="2023-08-08"),
        ),
    ]
