# Generated by Django 4.2 on 2023-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_billing_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="total_paid",
            field=models.IntegerField(default=0),
        ),
    ]
