# Generated by Django 4.2 on 2023-08-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_remove_reservation_payment_reservation_view_booked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="created_at",
            field=models.DateField(default="2023-08-18"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="Date_Check_In",
            field=models.DateField(verbose_name="2023-08-18"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="Date_Check_In",
            field=models.DateField(default="2023-08-18"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="booked_on",
            field=models.DateField(blank=True, default="2023-08-18", null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="update_at",
            field=models.DateField(blank=True, default="2023-08-18", null=True),
        ),
    ]
